<html>
<head>
<title>news agreement</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body bgcolor="#FFFFFF">
<h3 align="center"><font face="Arial, Helvetica, sans-serif">1GARD International 
  Marketing Network </font></h3>
<h1 align="center"><b>Agreement on news service.</b></h1>
<table width="78%" border="0" align="center">
  <tr> 
    <td> 
      <hr>
      <p>You agree to place the news in the MARKETCHART <sup><font size="-1">sm</font></sup> 
        BUSINESS NEWS</p>
      <p>The editorial board reserves the right to examine, to accept or reject, 
        and to place the received materials to NEWS section.</p>
      <p> The requirements to the news contents. You agree that titles, texts 
        or digests should not contain the names and trade marks of the companies 
        or organizations with which your activity, business relationss, obligation 
        and so forth are not connected. The text should be finally edited for 
        the publication. You also agree that the information material, sent by 
        you, is examined by Editorial board which makes a decision on material 
        placing in Business News independently on the discretion. Editorial Board 
        does not correct, does not edit and does not give the recommendations 
        concerning improvement of the press release. The contents of the press 
        release should not contain material that is violent, threatening, harmful,obscene, 
        pornographic, unlawful, discriminatory, defamatory, infringing, harassing 
        or offensive. The editorial board does not examine materials containing 
        the information, which can be recognized as illegal in some countries 
        (trade of drugs, weapon, prostitution, violence, pornography, disclosing 
        of personal life secrets of the persons etc.). You agree that only you 
        are responsible for the contents, truthfulness, conformity to the reality, 
        objectivity of information materials sent by you. </p>
      <p><b>If not agree - please, do not use this service.</b></p>
      <p><b>If you agree, follow the instructions: </b></p>
      </td>
  </tr>
  <tr> 
    <td>
      <h1 align="center">How to place NEWS.</h1>
      <hr>
      <p>You can to send the news by e-mail to:<br>
        news@1gard.com</p>
      <h2>E-mail Feeling Requirements.</h2>
      <p><b>NOTE!</b><i> <b>The red symbols are required.</b></i></p>
      <p><i>Indicate in the SUBJECT field</i>: <font color="#FF0000">news</font></p>
      <p><i>In the main body mail text:</i></p>
      <p><font color="#FF0000">[member]</font></p>
      <p><font color="#FF0000">logname=</font>your member's login name</p>
      <p><font color="#FF0000">company id=</font>your company's ID</p>
      <p><font color="#FF0000">[about]</font></p>
      <p><font color="#FF0000">author=</font>author's name</p>
      <p><font color="#FF0000">title=</font>the title of the news</p>
      <p><font color="#FF0000">[digest]</font></p>
      <p>The short description of the news you would to send.</p>
      <p><font color="#FF0000">[news]</font></p>
      <p>The body text of the news you would to send.</p>
      <hr>
      <h3>PHOTOS and IMAGES requirements</h3>
      <p>You can send the one image as the supplement to the press release.</p>
      <p>make it in GIF or JPG format, maximum 18K, resolution: maximum width 
        220 pixels.</p>
      <p>E-mail image file with the press-relise as attachment.</p>
      <hr>
    </td>
  </tr>
</table>
<div align="center"><a href="index.asp">Network home</a> <a href="area.asp">member's 
  area</a> </div>
</body>
</html>
